/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class App {

    public static final String SQL_SELECT_ALL_ARTISTS = "SELECT * FROM Artist";
    public static final String SQL_SELECT_ALL_ALBUMS = "SELECT * FROM Album";
    public static void main(String[] args) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://iths@127.0.0.1:3306/Chinook", "iths", "iths");
            ResultSet rs = con.createStatement().executeQuery(SQL_SELECT_ALL_ALBUMS);
            while(rs.next()) {
                System.out.println(rs.getString("Title"));
            }
        } catch (SQLException e) {
            System.err.println("hej det gick fel " + e);
        }
    }

    private void spaaKod(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://iths@127.0.0.1:3306/Chinook", "iths", "iths");
            System.out.println("vi klarade att koppla upp");
            ResultSet rs = con.createStatement().executeQuery(SQL_SELECT_ALL_ARTISTS);
            System.out.println("vi klarade att köra frågan!");
            while(rs.next()){
                long artistId = rs.getLong("ArtistId");
                String name = rs.getString("Name");
                System.out.println(new Artist(artistId, name));
            }
        } catch (SQLException e) {
            System.err.println("hej det gick fel " + e);
        }
    }
}
